const TABLES = {
  USER: "USER",
  CATEGORY: "CATEGORY",
  COMPANY_DETAIL: "COMPANY_DETAIL",
  MASTER: "MASTER",
  PERSON: "COMP_PERSON",
  EVENTS: "EVENTS",
  TAGS: "TAGS",
  TAGS_MAPPING: "TAGS_MAPPING",
};

module.exports = { TABLES };
