const TABLES = {
  USER: "USER",
  CATEGORY: "CATEGORY",
  COMPANY_DETAIL: "COMPANY_DETAIL",
  COMP_MASTER: "COMP_MASTER",
  COMP_PERSON: "COMP_PERSON",
  EVENTS: "EVENTS",
  TAGS: "TAGS",
  TAGS_MAPPING: "TAGS_MAPPING",
  INDSEGMENT: "INDSEGMENT",
  COMP_SEGMENT_MAP: "COMP_SEGMENT_MAP",
  COMP_EXH_HISTORY: "COMP_EXH_HISTORY",
  COMP_PERSON_EXH_HISTORY: "COMP_PERSON_EXH_HISTORY",
  DATA_SOURCE: "DATA_SOURCE",
  COMPANY_UPDATE_HISTORY: "COMPANY_UPDATE_HISTORY",
  COMP_PERSON_UPDATE_HISTORY: "COMP_PERSON_UPDATE_HISTORY",
  EVENTS_ATTENDEE: "SOURCE_PERSON"
};

module.exports = { TABLES };
